@url_dev=http://localhost:3000/v1/api/product
@x-api-key=39e4486ffe979b3b4334e8c64f4ee733a1843ccfbb8c18e27d2eaebbe8d5eedae56db9ed45f84ba79025dfdd6015fa0e666a6b1feab4de5c54f68340c90b6bab
@x-client-id=68861793636425c6732d27fa
@authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODg2MTc5MzYzNjQyNWM2NzMyZDI3ZmEiLCJlbWFpbCI6Im5ndXllbjE1QGdtYWlsLmNvbSIsImlhdCI6MTc1Mzc4NTYyMCwiZXhwIjoxNzUzOTU4NDIwfQ.KI7Uz6nuE5KvXsSgqqo2DOkTPWubO7UZ3Va2GPDUBc0
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODg2MTc5MzYzNjQyNWM2NzMyZDI3ZmEiLCJlbWFpbCI6Im5ndXllbjE1QGdtYWlsLmNvbSIsImlhdCI6MTc1Mzc4MDcyMCwiZXhwIjoxNzU0Mzg1NTIwfQ.BgcSmJiCSPamnFhKkTGEdNKk1G05J9B-NvrKCdBZvPU
@product_id=6888b37163db2e3ea5cbd3ce
###! QUERY
### GET all
GET {{url_dev}}
x-api-key: {{x-api-key}}
### GET one
GET {{url_dev}}/{{product_id}}
x-api-key: {{x-api-key}}

### GET list search product
GET {{url_dev}}/search/Iphone
x-api-key: {{x-api-key}}

### GET drafts all
GET  {{url_dev}}/drafts/all
Content-Type: application/json
x-api-key: {{x-api-key}}
x-client-id: {{x-client-id}}
authorization: {{authorization}}

### GET published all
GET {{url_dev}}/published/all
Content-Type: application/json
x-api-key: {{x-api-key}}
x-client-id: {{x-client-id}}
authorization: {{authorization}}

###
@product_id=6888c551421acc89af72f509
###! POST 
### publish product
POST {{url_dev}}/publish/{{product_id}}
Content-Type: application/json
x-api-key: {{x-api-key}}
x-client-id: {{x-client-id}}
authorization: {{authorization}}

### unpublish product
POST {{url_dev}}/unpublish/{{product_id}}
Content-Type: application/json
x-api-key: {{x-api-key}}
x-client-id: {{x-client-id}}
authorization: {{authorization}}

###! create product
### create product = electronics
POST {{url_dev}}
Content-Type: application/json
x-api-key: {{x-api-key}}
x-client-id: {{x-client-id}}
authorization: {{authorization}}

{
  "product_name": "Iphone 55",
  "product_thumb": "https://example.com/img/headphones.jpg",
  "product_description": "Noise-canceling over-ear headphones",
  "product_price": 2500000,
  "product_quantity": 100,
  "product_type": "Electronics",
  "product_shop": "{{x-client-id}}",
  "product_attributes": {
    "manufacturer": "Apple 5",
    "model": "Iphone 14",
    "color": "Gold",
    "product_shop": "{{x-client-id}}"
  }
}

### create product = clothing
POST {{url_dev}}
Content-Type: application/json
x-api-key: {{x-api-key}}
x-client-id: {{x-client-id}}
authorization: {{authorization}}

{
  "product_name": "Furniture",
  "product_thumb": "https://example.com/img/new-jean.jpg",
  "product_description": "Slim-fit jeans made with recycled materials",
  "product_price": 1200000,
  "product_quantity": 50,
  "product_type": "Clothing",
  "product_shop": "{{x-client-id}}", 
  "product_attributes": {
    "brand": "Levi's55",
    "size": "M",
    "material": "Denim"
  }
}

###  create product = Furniture
POST {{url_dev}}
Content-Type: application/json
x-api-key: {{x-api-key}}
x-client-id: {{x-client-id}}
authorization: {{authorization}}

{
  "product_name": "Furnitures",
  "product_thumb": "https://example.com/img/new-jean.jpg",
  "product_description": "Slim-fit jeans made with recycled materials",
  "product_price": 1200000,
  "product_quantity": 50,
  "product_type": "Furniture",
  "product_shop": "{{x-client-id}}", 
  "product_attributes": {
    "brand": "Levi's55",
    "size": "M",
    "material": "Denim"
  }
}


