@url_dev=http://localhost:3000/v1/api/product
@x-api-key=39e4486ffe979b3b4334e8c64f4ee733a1843ccfbb8c18e27d2eaebbe8d5eedae56db9ed45f84ba79025dfdd6015fa0e666a6b1feab4de5c54f68340c90b6bab
@x-client-id=68861793636425c6732d27fa
@authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODg2MTc5MzYzNjQyNWM2NzMyZDI3ZmEiLCJlbWFpbCI6Im5ndXllbjE1QGdtYWlsLmNvbSIsImlhdCI6MTc1Mzc1ODc3NSwiZXhwIjoxNzUzOTMxNTc1fQ.jcRxmHZiresrpnRC8nkg2zDFoV83yDtvdWsCNwphs6Y
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODg2MTc5MzYzNjQyNWM2NzMyZDI3ZmEiLCJlbWFpbCI6Im5ndXllbjE1QGdtYWlsLmNvbSIsImlhdCI6MTc1Mzc1ODc3NSwiZXhwIjoxNzU0MzYzNTc1fQ.im_io1PuoRlY5DBzY3VPr_hw5cwWrp5x5Pl3wuinakg

### create product
POST {{url_dev}}
Content-Type: application/json
x-api-key: {{x-api-key}}
x-client-id: {{x-client-id}}
authorization: {{authorization}}

{
  "product_name": "New Jean",
  "product_thumb": "https://example.com/img/new-jean.jpg",
  "product_description": "Slim-fit jeans made with recycled materials",
  "product_price": 1200000,
  "product_quantity": 50,
  "product_type": "Clothing",
  "product_shop": "{{x-client-id}}", 
  "product_attributes": {
    "brand": "Levi's",
    "size": "M",
    "material": "Denim"
  }
}

